# Generated by Django 5.2.5 on 2025-08-20 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Original query text from user')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('procedure', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('policy_age', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('payout', models.DecimalField(blank=True, decimal_places=2, help_text='Payout amount in INR', max_digits=10, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Insurance Query',
                'verbose_name_plural': 'Insurance Queries',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='claims.insurancequery')),
            ],
            options={
                'verbose_name': 'Claim Reason',
                'verbose_name_plural': 'Claim Reasons',
                'ordering': ['order'],
            },
        ),
    ]
